# OPTIMIZED CONFIGURATION
# Based on analysis of prediction results
# Fixes critical issues:
# 1. R² ≈ 0 → More data, better features, regularization
# 2. Flat predictions → Calibration, adaptive thresholds
# 3. 0% down accuracy → Asymmetric thresholds, class balancing

data_download:
  stocks_list:
    - AAPL
    - GOOGL
    - META
    - NVDA
    - TSLA
  start_date: '2018-01-01'  # Più storia (7 anni invece di 5)
  end_date: null

features:
  # Basic technical (esistenti)
  technical_indicators:
    - SMA_20
    - SMA_50
    - SMA_200
    - EMA_12
    - EMA_26
    - MACD
    - RSI_14
    - BB_upper
    - BB_lower
    - ATR_14

  # 🆕 ADVANCED: Market regime (CRITICO)
  market_regime:
    enabled: true
    features:
      - ADX
      - Trend_Strength
      - Market_Regime  # Bull/Bear/Sideways
      - Regime_Change

  # 🆕 ADVANCED: Volatility clustering (CRITICO)
  volatility_features:
    enabled: true
    windows: [5, 10, 20, 60]
    features:
      - RealizedVol
      - ParkinsonVol
      - VolOfVol
      - Vol_Regime
      - Vol_Spike

  # 🆕 ADVANCED: Microstructure
  microstructure:
    enabled: true
    features:
      - High_Low_Range
      - Body_Size
      - Candlestick_Patterns
      - Price_Action_Momentum

  # 🆕 ADVANCED: Non-linear transforms
  non_linear:
    enabled: true
    features:
      - Returns_Squared
      - Returns_Cubed
      - Log_transforms
      - Interactions
      - Cyclical_time

  # Sentiment (opzionale ma utile)
  sentiment:
    enabled: true
    sources:
      - news_headlines

  # Macro-economic (opzionale)
  macro_economic:
    enabled: true
    indicators:
      - FEDFUNDS
      - DGS10
      - VIXCLS

# MODEL CONFIGURATION - OTTIMIZZATO
models:
  xgboost:
    enabled: true
    params:
      n_estimators: 1500        # Più trees (era 500)
      max_depth: 5              # Meno depth per evitare overfit (era 7)
      learning_rate: 0.01       # Più lento ma accurato (era 0.05)
      subsample: 0.7            # Più aggressivo (era 0.8)
      colsample_bytree: 0.7     # Più feature sampling (era 0.8)
      gamma: 0.5                # Più pruning (era 0.1)
      min_child_weight: 5       # Più conservativo (era 1)
      reg_alpha: 0.3            # L1 regularization (era 0.1)
      reg_lambda: 2.0           # L2 regularization (era 1.0)
      random_state: 42

  lightgbm:
    enabled: true
    params:
      n_estimators: 1500        # Più trees
      max_depth: 5              # Meno depth
      learning_rate: 0.01       # Più lento
      num_leaves: 31            # OK
      subsample: 0.7            # Più sampling
      colsample_bytree: 0.7
      min_data_in_leaf: 30      # Più conservativo (era 20)
      min_gain_to_split: 0.01   # Evita split inutili
      reg_alpha: 0.3            # L1 reg
      reg_lambda: 2.0           # L2 reg
      random_state: 42

  lstm:
    enabled: true
    params:
      sequence_length: 120      # Più storia (era 60)
      lstm_units: [256, 128, 64] # Più capacità
      dropout: 0.3              # Più dropout (era 0.2)
      recurrent_dropout: 0.2    # 🆕 Dropout nelle connessioni
      epochs: 150               # Più epochs (era 100)
      batch_size: 64            # Batch più grande
      learning_rate: 0.0005     # Più lento (era 0.001)
      early_stopping_patience: 30  # Più pazienza

  timesfm:
    enabled: false  # Disabilita per velocità (opzionale)
    model_name: "google/timesfm-2.5-200m-pytorch"
    params:
      context_length: 512
      horizon_length: 30
      backend: "gpu"

  ensemble:
    enabled: true
    method: "weighted_average"
    optimization: true

    # 🆕 CRITICAL: Calibration
    calibration:
      enabled: true
      method: "variance_scaling"

    # 🆕 CRITICAL: Adaptive thresholds
    adaptive_thresholds:
      enabled: true
      method: "quantile_based"
      optimize_on_validation: true

    # 🆕 NEW: Uncertainty quantification
    uncertainty:
      enabled: true
      min_confidence: 0.6  # Solo trade con confidence > 60%

# PREDICTION CONFIGURATION
prediction:
  horizons: [1, 5, 10, 20]  # Multiple horizons
  targets:
    - direction
    - returns
    - price

  confidence_intervals: true
  confidence_level: 0.95

  # 🆕 NEW: Calibrated predictions
  use_calibration: true
  use_adaptive_thresholds: true

# TRAINING CONFIGURATION - OTTIMIZZATO
training:
  validation_split: 0.15    # Meno validation (era 0.2)
  test_split: 0.10          # OK
  walk_forward: true

  # 🆕 NEW: Cross-validation rigorosa
  cross_validation:
    enabled: true
    n_folds: 5
    method: "time_series"

  early_stopping:
    enabled: true
    patience: 30            # Più pazienza (era 20)
    monitor: 'val_loss'
    min_delta: 0.0001       # Più sensibile

  # 🆕 NEW: Learning rate scheduling
  lr_schedule:
    enabled: true
    method: "reduce_on_plateau"
    factor: 0.5
    patience: 10

  # Hyperparameter tuning (opzionale, lento)
  hyperparameter_tuning:
    enabled: false
    n_trials: 100
    timeout: 7200  # 2 hours

# BACKTESTING - OTTIMIZZATO
backtesting:
  enabled: true
  initial_capital: 100000
  commission: 0.001  # 0.1%
  slippage: 0.0005   # 0.05%

  strategies:
    # Strategy 1: Threshold con calibration
    - name: calibrated_threshold
      type: threshold_based
      params:
        use_calibration: true
        use_adaptive_thresholds: true
        min_confidence: 0.6
        hold_days: 3

    # Strategy 2: Top-K più aggressivo
    - name: aggressive_topk
      type: top_k
      params:
        k: 3                    # Top 3 stocks
        rebalance_days: 3       # Più frequente (era 5)
        use_stop_loss: true     # 🆕 Stop loss
        stop_loss_pct: -0.05    # -5%

    # Strategy 3: Confidence-based (NUOVO)
    - name: confidence_based
      type: confidence_weighted
      params:
        min_confidence: 0.7
        position_sizing: "confidence"  # Size = confidence
        max_position: 0.3      # Max 30% per stock

  # Risk management (NUOVO)
  risk_management:
    enabled: true
    max_position_size: 0.3     # Max 30% in single stock
    max_daily_loss: 0.02       # Stop trading if -2% daily
    max_drawdown: 0.20         # Reduce positions at -20%

  metrics:
    - sharpe_ratio
    - sortino_ratio
    - calmar_ratio
    - max_drawdown
    - win_rate
    - profit_factor
    - total_return
    - annual_return
    - avg_trade_duration

# OUTPUT CONFIGURATION
output:
  save_models: true
  save_predictions: true
  save_features: true

  # 🆕 NEW: Auto-generate analysis
  auto_analysis:
    enabled: true
    generate_dashboard: true
    dashboard_file: "prediction_analysis.html"

  reports:
    - performance_summary
    - feature_importance
    - prediction_analysis
    - backtest_results
    - calibration_metrics  # 🆕 NEW

  format: ['csv', 'json', 'html']

# LOGGER
logger:
  log_level: 'INFO'
  log_file: 'logs/prediction_system.log'

# API KEYS
api_keys:
  news_api: 'NEWS_API_KEY'
  fred_api: 'FRED_API_KEY'

# 🆕 OPTIMIZATION SETTINGS
optimization:
  # Auto-tune based on validation performance
  auto_tune:
    enabled: false  # Set true per auto-tuning
    metric: "directional_accuracy"  # Optimize for this
    max_iterations: 50

  # Feature selection
  feature_selection:
    enabled: true
    method: "importance_based"
    keep_top_n: 80  # Keep top 80 features
    min_importance: 0.001