# Optimized Configuration for Better Predictions

data_download:
  stocks_list:
    - AAPL
    - GOOGL
  start_date: '2020-01-01'  # More data = better predictions
  end_date: null

features:
  technical_indicators:
    # Momentum
    - RSI_14
    - RSI_7
    - STOCH_k
    - STOCH_d
    - Williams_R
    - ROC_10

    # Trend
    - MACD
    - MACD_signal
    - MACD_hist
    - ADX

    # Volatility
    - BB_upper
    - BB_middle
    - BB_lower
    - ATR_14

    # Volume
    - OBV
    - MFI_14
    - AD  # Accumulation/Distribution

  price_features:
    - Returns_1d
    - Returns_2d
    - Returns_5d
    - Returns_10d
    - Returns_20d
    - Log_returns
    - Volatility_5
    - Volatility_20

  advanced_features:
    enabled: false  # Use our improved feature engineering instead


  feature_selection:
    enabled: true
    method: 'mutual_info'
    keep_top_n: 50  # Keep only best features

models:
  xgboost:
    enabled: true
    params:
      n_estimators: 500
      max_depth: 4  # Reduced to prevent overfitting
      learning_rate: 0.01  # Lower for better generalization
      subsample: 0.7
      colsample_bytree: 0.7
      gamma: 0.2
      reg_alpha: 0.5
      reg_lambda: 2.0
      min_child_weight: 5
      random_state: 42
      early_stopping_rounds: 50

  lightgbm:
    enabled: true
    params:
      n_estimators: 500
      max_depth: 4
      learning_rate: 0.01
      num_leaves: 15  # Reduced from 31
      subsample: 0.7
      colsample_bytree: 0.7
      reg_alpha: 0.5
      reg_lambda: 2.0
      min_child_samples: 20
      random_state: 42
      early_stopping_rounds: 50

  lstm:
    enabled: false  # Disable until fixed
    params:
      sequence_length: 30  # Reduced from 60
      lstm_units: [64, 32]  # Simpler architecture
      dropout: 0.3
      epochs: 50
      batch_size: 16
      learning_rate: 0.0005
      early_stopping_patience: 10

  timesfm:
    enabled: false  # Disable for now

  ensemble:
    enabled: true
    method: "optimized_weights"
    optimization: true

training:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15

  # Cross-validation
  cross_validation:
    enabled: true
    n_splits: 5

prediction:
  horizons: [1, 5, 20]
  confidence_level: 0.95

backtesting:
  initial_capital: 10000
  commission: 0.001  # 0.1%
  slippage: 0.001

  strategies:
    - name: threshold_based
      params:
        buy_threshold: 0.002  # Reduced from 0.01
        sell_threshold: -0.002
        hold_period: 1

    - name: top_k
      params:
        k: 3
        rebalance_frequency: 5

    - name: momentum
      params:
        lookback: 20
        threshold: 0.1

output:
  save_predictions: true
  save_models: true
  save_features: true
  generate_report: true
  output_dir: 'outputs'